
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 01 15:32:42 CEST 2017
//----------------------------------------------------

package parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RBRACK = 25;
  public static final int LT = 19;
  public static final int NE = 18;
  public static final int IDENT = 32;
  public static final int ASGN = 29;
  public static final int ELSE = 4;
  public static final int PLUS = 13;
  public static final int RPAREN = 21;
  public static final int LCURL = 24;
  public static final int WHILE = 6;
  public static final int STAR = 15;
  public static final int SLASH = 16;
  public static final int LBRACK = 26;
  public static final int REF = 7;
  public static final int IF = 3;
  public static final int COLON = 28;
  public static final int LPAREN = 22;
  public static final int GT = 20;
  public static final int LE = 11;
  public static final int OF = 9;
  public static final int INTLIT = 31;
  public static final int SEMIC = 27;
  public static final int TYPE = 10;
  public static final int COMMA = 30;
  public static final int EOF = 0;
  public static final int GE = 12;
  public static final int MINUS = 14;
  public static final int error = 1;
  public static final int PROC = 8;
  public static final int EQ = 17;
  public static final int RCURL = 23;
  public static final int ARRAY = 2;
  public static final int VAR = 5;
}

